"""added votes

Revision ID: 078327150a27
Revises: f589bf711384
Create Date: 2023-01-21 00:51:55.272547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078327150a27'
down_revision = 'f589bf711384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('launched_ui', sa.Integer(), nullable=False),
    sa.Column('target_ui', sa.Integer(), nullable=False),
    sa.Column('rep_num', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['launched_ui'], ['users.row_id'], name=op.f('fk__votes__launched_ui__users')),
    sa.ForeignKeyConstraint(['target_ui'], ['users.row_id'], name=op.f('fk__votes__target_ui__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__votes'))
    )
    op.create_unique_constraint(op.f('uq__users__row_id'), 'users', ['row_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__row_id'), 'users', type_='unique')
    op.drop_table('votes')
    # ### end Alembic commands ###
