"""Initial

Revision ID: 70d222071fc2
Revises: 
Create Date: 2023-01-05 18:09:40.651919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d222071fc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('today_pdr', sa.Integer(), nullable=True),
    sa.Column('today_pass', sa.Integer(), nullable=True),
    sa.Column('year_pdr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__chats'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('pdr_num', sa.Integer(), nullable=True),
    sa.Column('fucked', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('pdr_of_the_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk__users__chat_id__chats')),
    sa.PrimaryKeyConstraint('id', 'chat_id', name=op.f('pk__users')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
    )
    op.create_table('launch_info',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('day_phrase', sa.String(), nullable=True),
    sa.Column('up_to_date_phrase', sa.Boolean(), nullable=True),
    sa.Column('daily_launch_date', sa.Date(), nullable=True),
    sa.Column('year_launch_num', sa.Integer(), nullable=True),
    sa.Column('who_launched', sa.Integer(), nullable=True),
    sa.Column('launch_streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk__launch_info__chat_id__chats')),
    sa.ForeignKeyConstraint(['who_launched'], ['users.id'], name=op.f('fk__launch_info__who_launched__users')),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk__launch_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launch_info')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
