"""Added tag_photo_item

Revision ID: 76482a13d7c9
Revises: 611184cc4070
Create Date: 2023-01-14 20:39:40.176644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76482a13d7c9'
down_revision = '611184cc4070'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('attachment_str', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk__tags_photos__inventory_id__inventory')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__tags_photos'))
    )
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_table('tags_photos')
    # ### end Alembic commands ###
